### ISSUE TITLE
CGRectMake -> auto convert

### ISSUE THREAD

**Issue by johndpope** [BellGeorge/objc2swift.io#4]
CGRectMake(width - 80, 40, 81, 20) >

**Comment by epreston** [comment]
Slightly off topic but related idea:

This points to the fact that we should have two levels of translation.  The first level is a functionally equivalent translation, the second level is a more semantic cleanup.  This may be completed in one step in the implementation.  This second logical level catches the "yeah, that has the same result but you don't write it like that in Swift" cases.
